// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Bond } from '../frac/bond.js';
import { Fragment } from '../frac/fragment.js';
import { Hull } from '../frac/hull.js';
import { HullFaces } from '../frac/hull-faces.js';
import { Loop } from '../frac/loop.js';
import { SpawnPoint } from '../frac/spawn-point.js';


export class Asset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Asset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAsset(bb:flatbuffers.ByteBuffer, obj?:Asset):Asset {
  return (obj || new Asset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAsset(bb:flatbuffers.ByteBuffer, obj?:Asset):Asset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Asset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('FRAC');
}

schemaVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

toolVersion():string|null
toolVersion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toolVersion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

settingsHash():string|null
settingsHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
settingsHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

materialLibraryId():string|null
materialLibraryId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
materialLibraryId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

materialLibraryVersion():string|null
materialLibraryVersion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
materialLibraryVersion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fragments(index: number, obj?:Fragment):Fragment|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Fragment()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fragmentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

bonds(index: number, obj?:Bond):Bond|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Bond()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bondsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

hulls(index: number, obj?:Hull):Hull|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Hull()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

hullsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

hullFaces(index: number, obj?:HullFaces):HullFaces|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new HullFaces()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

hullFacesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

loops(index: number, obj?:Loop):Loop|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new Loop()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

loopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

levels():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

spawn(index: number, obj?:SpawnPoint):SpawnPoint|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new SpawnPoint()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 24, this.bb!) : null;
}

spawnLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

variant():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

levelFragmentBegin(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

levelFragmentBeginLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

levelFragmentBeginArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

levelFragmentCount(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

levelFragmentCountLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

levelFragmentCountArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * Child bond ids; Bond.child_begin/child_count index into this (appended).
 */
bondChildren(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

bondChildrenLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

bondChildrenArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startAsset(builder:flatbuffers.Builder) {
  builder.startObject(18);
}

static addSchemaVersion(builder:flatbuffers.Builder, schemaVersion:number) {
  builder.addFieldInt16(0, schemaVersion, 0);
}

static addToolVersion(builder:flatbuffers.Builder, toolVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, toolVersionOffset, 0);
}

static addSettingsHash(builder:flatbuffers.Builder, settingsHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, settingsHashOffset, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(3, seed, BigInt('0'));
}

static addMaterialLibraryId(builder:flatbuffers.Builder, materialLibraryIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, materialLibraryIdOffset, 0);
}

static addMaterialLibraryVersion(builder:flatbuffers.Builder, materialLibraryVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, materialLibraryVersionOffset, 0);
}

static addFragments(builder:flatbuffers.Builder, fragmentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, fragmentsOffset, 0);
}

static createFragmentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFragmentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBonds(builder:flatbuffers.Builder, bondsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, bondsOffset, 0);
}

static createBondsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBondsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHulls(builder:flatbuffers.Builder, hullsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, hullsOffset, 0);
}

static createHullsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHullsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHullFaces(builder:flatbuffers.Builder, hullFacesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, hullFacesOffset, 0);
}

static createHullFacesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHullFacesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLoops(builder:flatbuffers.Builder, loopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, loopsOffset, 0);
}

static createLoopsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLoopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLevels(builder:flatbuffers.Builder, levels:number) {
  builder.addFieldInt8(11, levels, 0);
}

static addSpawn(builder:flatbuffers.Builder, spawnOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, spawnOffset, 0);
}

static startSpawnVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(24, numElems, 4);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, nameOffset, 0);
}

static addVariant(builder:flatbuffers.Builder, variant:number) {
  builder.addFieldInt32(14, variant, 0);
}

static addLevelFragmentBegin(builder:flatbuffers.Builder, levelFragmentBeginOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, levelFragmentBeginOffset, 0);
}

static createLevelFragmentBeginVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createLevelFragmentBeginVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createLevelFragmentBeginVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startLevelFragmentBeginVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLevelFragmentCount(builder:flatbuffers.Builder, levelFragmentCountOffset:flatbuffers.Offset) {
  builder.addFieldOffset(16, levelFragmentCountOffset, 0);
}

static createLevelFragmentCountVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createLevelFragmentCountVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createLevelFragmentCountVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startLevelFragmentCountVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBondChildren(builder:flatbuffers.Builder, bondChildrenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, bondChildrenOffset, 0);
}

static createBondChildrenVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createBondChildrenVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createBondChildrenVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startBondChildrenVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishAssetBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'FRAC');
}

static finishSizePrefixedAssetBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'FRAC', true);
}

static createAsset(builder:flatbuffers.Builder, schemaVersion:number, toolVersionOffset:flatbuffers.Offset, settingsHashOffset:flatbuffers.Offset, seed:bigint, materialLibraryIdOffset:flatbuffers.Offset, materialLibraryVersionOffset:flatbuffers.Offset, fragmentsOffset:flatbuffers.Offset, bondsOffset:flatbuffers.Offset, hullsOffset:flatbuffers.Offset, hullFacesOffset:flatbuffers.Offset, loopsOffset:flatbuffers.Offset, levels:number, spawnOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, variant:number, levelFragmentBeginOffset:flatbuffers.Offset, levelFragmentCountOffset:flatbuffers.Offset, bondChildrenOffset:flatbuffers.Offset):flatbuffers.Offset {
  Asset.startAsset(builder);
  Asset.addSchemaVersion(builder, schemaVersion);
  Asset.addToolVersion(builder, toolVersionOffset);
  Asset.addSettingsHash(builder, settingsHashOffset);
  Asset.addSeed(builder, seed);
  Asset.addMaterialLibraryId(builder, materialLibraryIdOffset);
  Asset.addMaterialLibraryVersion(builder, materialLibraryVersionOffset);
  Asset.addFragments(builder, fragmentsOffset);
  Asset.addBonds(builder, bondsOffset);
  Asset.addHulls(builder, hullsOffset);
  Asset.addHullFaces(builder, hullFacesOffset);
  Asset.addLoops(builder, loopsOffset);
  Asset.addLevels(builder, levels);
  Asset.addSpawn(builder, spawnOffset);
  Asset.addName(builder, nameOffset);
  Asset.addVariant(builder, variant);
  Asset.addLevelFragmentBegin(builder, levelFragmentBeginOffset);
  Asset.addLevelFragmentCount(builder, levelFragmentCountOffset);
  Asset.addBondChildren(builder, bondChildrenOffset);
  return Asset.endAsset(builder);
}
}
