// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class BondComposition {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BondComposition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBondComposition(bb:flatbuffers.ByteBuffer, obj?:BondComposition):BondComposition {
  return (obj || new BondComposition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBondComposition(bb:flatbuffers.ByteBuffer, obj?:BondComposition):BondComposition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BondComposition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * InterfaceKind (0 monolithic, 1 mortar_joint, 2 weld, 3 bolted,
 * 4 cold_joint, 5 grain_boundary, 6 adhesive, 7 component_connection,
 * 8 anchor, 9 bearing).
 */
kind():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * Interface material id, -1 if none.
 */
interfaceMaterial():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

/**
 * Area fraction of the bond with this composition.
 */
fraction():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startBondComposition(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKind(builder:flatbuffers.Builder, kind:number) {
  builder.addFieldInt8(0, kind, 0);
}

static addInterfaceMaterial(builder:flatbuffers.Builder, interfaceMaterial:number) {
  builder.addFieldInt32(1, interfaceMaterial, -1);
}

static addFraction(builder:flatbuffers.Builder, fraction:number) {
  builder.addFieldFloat32(2, fraction, 0.0);
}

static endBondComposition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBondComposition(builder:flatbuffers.Builder, kind:number, interfaceMaterial:number, fraction:number):flatbuffers.Offset {
  BondComposition.startBondComposition(builder);
  BondComposition.addKind(builder, kind);
  BondComposition.addInterfaceMaterial(builder, interfaceMaterial);
  BondComposition.addFraction(builder, fraction);
  return BondComposition.endBondComposition(builder);
}
}
