// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BondComposition } from '../frac/bond-composition.js';
import { Vec2 } from '../frac/vec2.js';
import { Vec3 } from '../frac/vec3.js';


export class Bond {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Bond {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBond(bb:flatbuffers.ByteBuffer, obj?:Bond):Bond {
  return (obj || new Bond()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBond(bb:flatbuffers.ByteBuffer, obj?:Bond):Bond {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Bond()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

a():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Fragment B, or -1 for a world anchor.
 */
b():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

area():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

centroid(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Unit normal oriented from A to B.
 */
normal(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

planarity():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

frameU(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

frameV(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Second moments of area about the centroid in the (u, v) frame, and the
 * polar moment j = i_uu + i_vv.
 */
iUu():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

iVv():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

iUv():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

j():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * In-plane oriented extent rectangle (center + half sizes along frame
 * axes).
 */
extentCenter(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

extentHalf(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

distA():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

distB():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

composition(index: number, obj?:BondComposition):BondComposition|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? (obj || new BondComposition()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

compositionLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rebarCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

rebarArea():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Unit rebar direction (zero when no rebar).
 */
rebarDir(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

strengthScale():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Parent bond id at the coarser level, -1 if none.
 */
parentBond():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

childBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

childCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

loopBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

loopCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

spawnBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

spawnCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

anchor():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * Number of fine cell interfaces aggregated into this bond (appended).
 */
interfaceCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startBond(builder:flatbuffers.Builder) {
  builder.startObject(32);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt8(1, level, 0);
}

static addA(builder:flatbuffers.Builder, a:number) {
  builder.addFieldInt32(2, a, 0);
}

static addB(builder:flatbuffers.Builder, b:number) {
  builder.addFieldInt32(3, b, 0);
}

static addArea(builder:flatbuffers.Builder, area:number) {
  builder.addFieldFloat32(4, area, 0.0);
}

static addCentroid(builder:flatbuffers.Builder, centroidOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, centroidOffset, 0);
}

static addNormal(builder:flatbuffers.Builder, normalOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, normalOffset, 0);
}

static addPlanarity(builder:flatbuffers.Builder, planarity:number) {
  builder.addFieldFloat32(7, planarity, 0.0);
}

static addFrameU(builder:flatbuffers.Builder, frameUOffset:flatbuffers.Offset) {
  builder.addFieldStruct(8, frameUOffset, 0);
}

static addFrameV(builder:flatbuffers.Builder, frameVOffset:flatbuffers.Offset) {
  builder.addFieldStruct(9, frameVOffset, 0);
}

static addIUu(builder:flatbuffers.Builder, iUu:number) {
  builder.addFieldFloat32(10, iUu, 0.0);
}

static addIVv(builder:flatbuffers.Builder, iVv:number) {
  builder.addFieldFloat32(11, iVv, 0.0);
}

static addIUv(builder:flatbuffers.Builder, iUv:number) {
  builder.addFieldFloat32(12, iUv, 0.0);
}

static addJ(builder:flatbuffers.Builder, j:number) {
  builder.addFieldFloat32(13, j, 0.0);
}

static addExtentCenter(builder:flatbuffers.Builder, extentCenterOffset:flatbuffers.Offset) {
  builder.addFieldStruct(14, extentCenterOffset, 0);
}

static addExtentHalf(builder:flatbuffers.Builder, extentHalfOffset:flatbuffers.Offset) {
  builder.addFieldStruct(15, extentHalfOffset, 0);
}

static addDistA(builder:flatbuffers.Builder, distA:number) {
  builder.addFieldFloat32(16, distA, 0.0);
}

static addDistB(builder:flatbuffers.Builder, distB:number) {
  builder.addFieldFloat32(17, distB, 0.0);
}

static addComposition(builder:flatbuffers.Builder, compositionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, compositionOffset, 0);
}

static createCompositionVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCompositionVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRebarCount(builder:flatbuffers.Builder, rebarCount:number) {
  builder.addFieldInt16(19, rebarCount, 0);
}

static addRebarArea(builder:flatbuffers.Builder, rebarArea:number) {
  builder.addFieldFloat32(20, rebarArea, 0.0);
}

static addRebarDir(builder:flatbuffers.Builder, rebarDirOffset:flatbuffers.Offset) {
  builder.addFieldStruct(21, rebarDirOffset, 0);
}

static addStrengthScale(builder:flatbuffers.Builder, strengthScale:number) {
  builder.addFieldFloat32(22, strengthScale, 0.0);
}

static addParentBond(builder:flatbuffers.Builder, parentBond:number) {
  builder.addFieldInt32(23, parentBond, -1);
}

static addChildBegin(builder:flatbuffers.Builder, childBegin:number) {
  builder.addFieldInt32(24, childBegin, 0);
}

static addChildCount(builder:flatbuffers.Builder, childCount:number) {
  builder.addFieldInt32(25, childCount, 0);
}

static addLoopBegin(builder:flatbuffers.Builder, loopBegin:number) {
  builder.addFieldInt32(26, loopBegin, 0);
}

static addLoopCount(builder:flatbuffers.Builder, loopCount:number) {
  builder.addFieldInt16(27, loopCount, 0);
}

static addSpawnBegin(builder:flatbuffers.Builder, spawnBegin:number) {
  builder.addFieldInt32(28, spawnBegin, 0);
}

static addSpawnCount(builder:flatbuffers.Builder, spawnCount:number) {
  builder.addFieldInt32(29, spawnCount, 0);
}

static addAnchor(builder:flatbuffers.Builder, anchor:boolean) {
  builder.addFieldInt8(30, +anchor, +false);
}

static addInterfaceCount(builder:flatbuffers.Builder, interfaceCount:number) {
  builder.addFieldInt32(31, interfaceCount, 0);
}

static endBond(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
