// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Mat3 } from '../frac/mat3.js';
import { Vec3 } from '../frac/vec3.js';


export class Fragment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Fragment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFragment(bb:flatbuffers.ByteBuffer, obj?:Fragment):Fragment {
  return (obj || new Fragment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFragment(bb:flatbuffers.ByteBuffer, obj?:Fragment):Fragment {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Fragment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * Parent fragment id, -1 for level-0 roots.
 */
parent():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

childBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

childCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

mass():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Center of mass (asset frame).
 */
com(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Inertia tensor about the center of mass, asset-frame axes.
 */
inertia(obj?:Mat3):Mat3|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Mat3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Material mix: parallel arrays of material ids and mass fractions.
 */
materialIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

materialIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

materialIdsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

materialFracs(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

materialFracsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

materialFracsArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

hullBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

hullCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

particleCandidate():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * ComponentRole (0 generic, 1 column, 2 beam, 3 slab, 4 wall,
 * 5 connection, 6 cosmetic, 7 prop, 8 glazing).
 */
role():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * glTF node index of this fragment in the render payload, -1 if none.
 */
gltfNode():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

volume():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

interiorArea():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

component():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

cellBegin():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

cellCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startFragment(builder:flatbuffers.Builder) {
  builder.startObject(20);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt8(1, level, 0);
}

static addParent(builder:flatbuffers.Builder, parent:number) {
  builder.addFieldInt32(2, parent, -1);
}

static addChildBegin(builder:flatbuffers.Builder, childBegin:number) {
  builder.addFieldInt32(3, childBegin, 0);
}

static addChildCount(builder:flatbuffers.Builder, childCount:number) {
  builder.addFieldInt32(4, childCount, 0);
}

static addMass(builder:flatbuffers.Builder, mass:number) {
  builder.addFieldFloat32(5, mass, 0.0);
}

static addCom(builder:flatbuffers.Builder, comOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, comOffset, 0);
}

static addInertia(builder:flatbuffers.Builder, inertiaOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, inertiaOffset, 0);
}

static addMaterialIds(builder:flatbuffers.Builder, materialIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, materialIdsOffset, 0);
}

static createMaterialIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createMaterialIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createMaterialIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startMaterialIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addMaterialFracs(builder:flatbuffers.Builder, materialFracsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, materialFracsOffset, 0);
}

static createMaterialFracsVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createMaterialFracsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createMaterialFracsVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startMaterialFracsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHullBegin(builder:flatbuffers.Builder, hullBegin:number) {
  builder.addFieldInt32(10, hullBegin, 0);
}

static addHullCount(builder:flatbuffers.Builder, hullCount:number) {
  builder.addFieldInt16(11, hullCount, 0);
}

static addParticleCandidate(builder:flatbuffers.Builder, particleCandidate:boolean) {
  builder.addFieldInt8(12, +particleCandidate, +false);
}

static addRole(builder:flatbuffers.Builder, role:number) {
  builder.addFieldInt8(13, role, 0);
}

static addGltfNode(builder:flatbuffers.Builder, gltfNode:number) {
  builder.addFieldInt32(14, gltfNode, -1);
}

static addVolume(builder:flatbuffers.Builder, volume:number) {
  builder.addFieldFloat32(15, volume, 0.0);
}

static addInteriorArea(builder:flatbuffers.Builder, interiorArea:number) {
  builder.addFieldFloat32(16, interiorArea, 0.0);
}

static addComponent(builder:flatbuffers.Builder, component:number) {
  builder.addFieldInt32(17, component, 0);
}

static addCellBegin(builder:flatbuffers.Builder, cellBegin:number) {
  builder.addFieldInt32(18, cellBegin, 0);
}

static addCellCount(builder:flatbuffers.Builder, cellCount:number) {
  builder.addFieldInt32(19, cellCount, 0);
}

static endFragment(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
