// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3 } from '../frac/vec3.js';


/**
 * Convex hull vertices (asset frame).
 */
export class Hull {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Hull {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHull(bb:flatbuffers.ByteBuffer, obj?:Hull):Hull {
  return (obj || new Hull()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHull(bb:flatbuffers.ByteBuffer, obj?:Hull):Hull {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Hull()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

vertices(index: number, obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec3()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
}

verticesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Owning fragment id (appended field).
 */
fragment():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startHull(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVertices(builder:flatbuffers.Builder, verticesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, verticesOffset, 0);
}

static startVerticesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
}

static addFragment(builder:flatbuffers.Builder, fragment:number) {
  builder.addFieldInt32(1, fragment, 0);
}

static endHull(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHull(builder:flatbuffers.Builder, verticesOffset:flatbuffers.Offset, fragment:number):flatbuffers.Offset {
  Hull.startHull(builder);
  Hull.addVertices(builder, verticesOffset);
  Hull.addFragment(builder, fragment);
  return Hull.endHull(builder);
}
}
