// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Row-major 3x3 matrix: m[3*row + col].
 */
export class Mat3 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Mat3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

m(index: number):number|null {
    return this.bb!.readFloat32(this.bb_pos + 0 + index * 4);
}

static sizeOf():number {
  return 36;
}

static createMat3(builder:flatbuffers.Builder, m: number[]|null):flatbuffers.Offset {
  builder.prep(4, 36);

  for (let i = 8; i >= 0; --i) {
    builder.writeFloat32((m?.[i] ?? 0));

  }

  return builder.offset();
}

}
