// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3 } from '../frac/vec3.js';


export class SpawnPoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpawnPoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

p(obj?:Vec3):Vec3|null {
  return (obj || new Vec3()).__init(this.bb_pos, this.bb!);
}

n(obj?:Vec3):Vec3|null {
  return (obj || new Vec3()).__init(this.bb_pos + 12, this.bb!);
}

static sizeOf():number {
  return 24;
}

static createSpawnPoint(builder:flatbuffers.Builder, p_x: number, p_y: number, p_z: number, n_x: number, n_y: number, n_z: number):flatbuffers.Offset {
  builder.prep(4, 24);
  builder.prep(4, 12);
  builder.writeFloat32(n_z);
  builder.writeFloat32(n_y);
  builder.writeFloat32(n_x);
  builder.prep(4, 12);
  builder.writeFloat32(p_z);
  builder.writeFloat32(p_y);
  builder.writeFloat32(p_x);
  return builder.offset();
}

}
